name: qr_scanner_app
description: A professional QR scanner app with auto copy and auto URL open toggles.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  qr_code_scanner: ^1.0.1

flutter:
  assets:
    - assets/icon.png
